name: Build CKAN Docker auxiliary images 

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs: 
  build:  
    runs-on: ubuntu-latest
    steps: 
    -  uses: actions/checkout@v2

    -  name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
      
    -  name: Set up QEMU
       uses: docker/setup-qemu-action@v1

    -  name: Apache build
       uses: docker/build-push-action@v2
       with:
          context: ./apache
          file: ./apache/Dockerfile
          push: false
          tags: opendatagis/ckan-docker-apache:test-build-only

    -  name: PostgreSQL build
       uses: docker/build-push-action@v2
       with:
          context: ./postgresql
          file: ./postgresql/Dockerfile
          push: false
          tags: opendatagis/ckan-docker-postgresql:test-build-only

    -  name: Solr build
       uses: docker/build-push-action@v2
       with:
          context: ./solr
          file: ./solr/Dockerfile
          push: false
          tags: opendatagis/ckan-docker-solr:test-build-only

    -  name: ckan-pycsw build
       uses: docker/build-push-action@v2
       with:
          context: ./ckan-pycsw
          file: ./solr/Dockerfile
          push: false
          tags: opendatagis/ckan-docker-solr:test-build-only